import UUID64 from './uuid64.js';
import { Identifiable } from './identifiable.js';
import { Text } from '@sc-voice/tools';
import { Levenshtein } from '@sc-voice/tools/dist/text/levenshtein.js';
import { DBG } from './defines.js';
import { Schema } from './schema.js';
import type { AvroType } from './schema.js';

const { Unicode, ColorConsole } = Text;
const { cc } = ColorConsole;
const { CHECKMARK: UOK } = Unicode;
const { FORMA: F3A } = DBG;

/**
 * IFormaMatcher - Strategy interface for matching Forma instances
 * Enables different matching algorithms (exact, fuzzy, prefix, name-based, etc.)
 * Matcher encapsulates both search value and matching logic
 */
export interface IFormaMatcher<T extends Forma> {
  /**
   * Calculate similarity score between search value and item
   * @param item - The item to compare
   * @returns Similarity score: 0 = no match, 1 = exact match
   */
  similarity(item: T): number;

  /**
   * Compare two items by similarity (descending: b - a)
   * @param a - First item
   * @param b - Second item
   * @returns Positive if b more similar, negative if a more similar, 0 if equal
   */
  compare(a: T, b: T): number;
}

/**
 * AFormaMatcher - Abstract base class providing default compare() implementation
 */
export abstract class AFormaMatcher<T extends Forma> implements IFormaMatcher<T> {
  abstract similarity(item: T): number;

  /**
   * Default compare implementation using similarity scores with ID tiebreaker
   * @param a - First item
   * @param b - Second item
   * @returns Descending order by similarity; if equal, compare by ID lexicographically
   */
  compare(a: T, b: T): number {
    const simDiff = this.similarity(b) - this.similarity(a);
    if (simDiff !== 0) return simDiff;

    // Tiebreaker: compare by ID base64 lexicographically for deterministic ordering
    if (a.id.base64 > b.id.base64) return 1;
    if (a.id.base64 < b.id.base64) return -1;
    return 0;
  }
}

/**
 * Forma - Base class for identifiable named objects
 *
 * ## Features
 * 1. **Named Identity**: Extends Identifiable with mutable `name` property
 *    - Default name format: `{PREFIX}-{UUID_PREFIX}` (e.g., "T2K-01234567" for Task instances)
 * 2. **Instance Tracking**: Static `#instances` map tracks count per class prefix
 *    - Prefix generated by abbreviating class name (first + count + last character)
 * 3. **Patching**: `patch(cfg)` method merges properties, only updates mutable fields (name)
 * 4. **Validation**: `validate(opts)` checks UUID v7 format and optional name prefix validation
 */
export class Forma extends Identifiable {
  static #instances: Record<string, number> = {};
  static patchableFields = ['name', 'summary'];
  #prefix: string = '';
  name: string;
  summary: string;

  constructor(cfg: any = {}) {
    const msg = 'f3a.ctor';
    const dbg = (F3A as any).CTOR;
    const { id } = cfg;
    // Identifiable constructor handles string-to-UUID64 conversion
    super(id);

    const prefix = this.#defaultPrefix();
    let instances = Forma.#instances[prefix] || 0;
    instances++;
    Forma.#instances[prefix] = instances;

    let { name } = cfg;
    if (name == null) {
      // this.id is UUID64 POJO with guaranteed base64 property
      name = this.id.timeId();
    }

    this.name = name;

    let { summary = `${this.constructor.name}?` } = cfg;
    this.summary = summary;

    dbg && cc.ok1(msg + UOK, { id: this.id, name });
  }

  /**
   * Register this class's avroSchema into the avro registry and return AvroType.
   *
   * @param opts Optional schema registration options (avro instance, registry)
   * @returns Registered AvroType from avro.parse()
   */
  static override registerAvro(opts: any = {}) {
    const msg = "f3a.registerAvro";
    const dbg = DBG.SCHEMA.ALL;
    Identifiable.registerAvro(opts);

    dbg>1 && cc.ok(msg, "registerType")
    let { fullName } = Forma.avroSchema;
    dbg>1 && cc.ok(msg, "registerType:", fullName)
    let avroType = Schema.registerType(Forma, opts);
    dbg && cc.ok1(msg, "schema:", fullName)
    return avroType
  }

  /**
   * Schema wrapper for Forma avro schema record
   * @returns Schema
   */
  static override get avroSchema(): Schema {
    return new Schema({
      name: 'Forma',
      namespace: 'scvoice.nameforma',
      type: 'record',
      fields: [
        { name: 'id', type: UUID64.avroSchema.fullName }, // immutable, unique, UUID64 POJO
        { name: 'name', type: 'string' }, // mutable
        { name: 'summary', type: 'string' }, // mutable
      ],
    });
  }

  /**
   * Abbreviate class name to prefix format: first + length-2 + last character.
   * Example: "Task" (4 chars) → "T2K" (first='T', length-2=2, last='K')
   * @param name - Class name to abbreviate
   * @returns Abbreviated prefix string
   */
  static abbreviateName(name: string) {
    let length = name.length;
    return [name[0], length - 2, name[length - 1]].join('');
  }

  /**
   * Get the instance prefix based on class name abbreviation.
   * Used for tracking instances and generating default names.
   * @returns Uppercase abbreviated prefix (e.g., "T2K" for Task)
   */
  #defaultPrefix() {
    return Forma.abbreviateName(this.constructor.name).toUpperCase();
  }

  /**
   * Validate UUID v7 format and optional name prefix validation.
   * @param opts - Validation options
   *   - defaultId: Check id is valid UUID64 (default: true)
   *   - defaultName: Check name starts with class prefix (default: false)
   * @returns true if valid, Error object if invalid
   */
  validate(opts: any = {}) {
    const msg = 'f3a.validate';
    const dbg = (DBG as any).FORMA.VALIDATE;
    const {
      defaultId = true, // id is UUID64
      defaultName = false, // name is derived from id
    } = opts;
    const { id, name } = this as any;
    let err;

    if (!err && defaultId) {
      if (!id.validate()) {
        err = new Error(`${msg} uuid64? ${id}`);
      }
    }
    if (!err && defaultName) {
      const prefix = this.#defaultPrefix();
      if (!name.startsWith(prefix)) {
        err = new Error(`${msg} defaultName? ${name}`);
      }
    }

    if (err) {
      dbg && cc.bad1(err.message);
      return err;
    }

    dbg && cc.ok1(msg + UOK, { id, name });
    return true;
  }

  override toString() {
    return this.name;
  }

  /**
   * Patch (merge) properties on this instance.
   * Only updates mutable fields (name, summary); immutable id is preserved.
   * @param cfg - Configuration object with properties to update
   */
  patch(cfg: any = {}) {
    let { name = this.name } = cfg;
    let { summary = this.summary } = cfg;
    this.name = name;
    this.summary = summary;
  }
}

/**
 * LevenshteinMatcher - Fuzzy matches Forma items by id using Levenshtein distance
 * Returns similarity score (0-1) where 1 = exact match, 0 = completely different
 */
export class LevenshteinMatcher<T extends Forma> extends AFormaMatcher<T> {
  /**
   * Create a Levenshtein matcher
   * @param searchValue - The id value to search for
   * @param ignoreCase - If true (default), comparison is case-insensitive
   */
  constructor(
    private searchValue: string,
    private ignoreCase: boolean = true
  ) {
    super();
  }

  /**
   * Calculate similarity score between searchValue and item id
   * @param item - Item to compare
   * @returns Similarity: 1 = exact match, 0 = no similarity
   */
  similarity(item: T): number {
    const msg = "f3a.simlarity";
    const s10e = this.ignoreCase ? this.searchValue.toLowerCase() : this.searchValue;

    const itemId = item.id;
    let itemIdStr = typeof itemId === 'string' ? itemId : itemId.base64;
    itemIdStr = this.ignoreCase ? itemIdStr.toLowerCase() : itemIdStr;

    // Compare against prefix of same length as search
    const compareStr = (s10e.length <= UUID64.TIME_SEQ_CHARS) 
      ? itemIdStr.substring(0, UUID64.TIME_SEQ_CHARS)
      : itemIdStr;
    //cc.tag1(msg, "TESTTAG1")

    // Use normalized distance (0-1), convert to similarity (1-0)
    const normalizedDistance = Levenshtein.normalizedDistance(s10e, compareStr);
    return 1 - normalizedDistance;
  }
}
