import UUID64 from './uuid64.js';
import { Identifiable } from './identifiable.js';
import { Text } from '@sc-voice/tools';
import { DBG } from './defines.js';
import { Schema } from './schema.js';

const { Unicode, ColorConsole } = Text;
const { cc } = ColorConsole;
const { CHECKMARK: UOK } = Unicode;
const { FORMA: F3A } = DBG;

/**
 * Forma - Base class for identifiable named objects
 *
 * ## Features
 * 1. **Named Identity**: Extends Identifiable with mutable `name` property
 *    - Default name format: `{PREFIX}-{UUID_PREFIX}` (e.g., "T2K-01234567" for Task instances)
 * 2. **Instance Tracking**: Static `#instances` map tracks count per class prefix
 *    - Prefix generated by abbreviating class name (first + count + last character)
 * 3. **Patching**: `patch(cfg)` method merges properties, only updates mutable fields (name)
 * 4. **Validation**: `validate(opts)` checks UUID v7 format and optional name prefix validation
 */
export class Forma extends Identifiable {
  static #instances: Record<string, number> = {};
  #prefix: string = '';
  name: string;

  constructor(cfg: any = {}) {
    const msg = 'f3a.ctor';
    const dbg = (F3A as any).CTOR;
    const { id } = cfg;
    // Identifiable constructor handles string-to-UUID64 conversion
    super(id);

    const prefix = this.#defaultPrefix();
    let instances = Forma.#instances[prefix] || 0;
    instances++;
    Forma.#instances[prefix] = instances;

    let { name } = cfg;
    if (name == null) {
      // this.id is UUID64 POJO with guaranteed base64 property
      name = this.id.timeId();
    }

    this.name = name;

    dbg && cc.ok1(msg + UOK, { id: this.id, name });
  }

  static get SCHEMA() {
    return {
      name: 'Forma',
      namespace: 'scvoice.nameforma',
      type: 'record',
      fields: [
        { name: 'id', type: UUID64.avroSchema }, // immutable, unique, UUID64 POJO
        { name: 'name', type: 'string' }, // mutable
      ],
    };
  }

  /**
   * Abbreviate class name to prefix format: first + length-2 + last character.
   * Example: "Task" (4 chars) → "T2K" (first='T', length-2=2, last='K')
   * @param name - Class name to abbreviate
   * @returns Abbreviated prefix string
   */
  static abbreviateName(name: string) {
    let length = name.length;
    return [name[0], length - 2, name[length - 1]].join('');
  }

  /**
   * Get the instance prefix based on class name abbreviation.
   * Used for tracking instances and generating default names.
   * @returns Uppercase abbreviated prefix (e.g., "T2K" for Task)
   */
  #defaultPrefix() {
    return Forma.abbreviateName(this.constructor.name).toUpperCase();
  }

  /**
   * Validate UUID v7 format and optional name prefix validation.
   * @param opts - Validation options
   *   - defaultId: Check id is valid UUID64 (default: true)
   *   - defaultName: Check name starts with class prefix (default: false)
   * @returns true if valid, Error object if invalid
   */
  validate(opts: any = {}) {
    const msg = 'f3a.validate';
    const dbg = (DBG as any).FORMA.VALIDATE;
    const {
      defaultId = true, // id is UUID64
      defaultName = false, // name is derived from id
    } = opts;
    const { id, name } = this as any;
    let err;

    if (!err && defaultId) {
      if (!id.validate()) {
        err = new Error(`${msg} uuid64? ${id}`);
      }
    }
    if (!err && defaultName) {
      const prefix = this.#defaultPrefix();
      if (!name.startsWith(prefix)) {
        err = new Error(`${msg} defaultName? ${name}`);
      }
    }

    if (err) {
      dbg && cc.bad1(err.message);
      return err;
    }

    dbg && cc.ok1(msg + UOK, { id, name });
    return true;
  }

  override toString() {
    return this.name;
  }

  /**
   * Patch (merge) properties on this instance.
   * Only updates mutable fields (name); immutable id is preserved.
   * @param cfg - Configuration object with properties to update
   */
  patch(cfg: any = {}) {
    let { name = this.name } = cfg;
    this.name = name;
  }
}
